services:
  investment-tracker:
    container_name: investment-tracker
    build: .
    ports:
      - "8000:8000"

  postgres:
    image: postgres:14.20-trixie
    container_name: postgres
    restart: always
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_DB-${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./migrations/db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}

volumes:
  postgres:


